In [1]:
import csv
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("diabetes_raw.csv")

In [3]:
m, n = data.shape

In [4]:
data

gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  diabetes  
0              6.6                  140         0  
1              6.6                   80         0  
2              5.7                  158         0  
3              5.0                  155         0  
4              4.8                  155         0  
...            ...                  ...       ...  
99995          6.2                   90         0  
99996          6.5                  100         0  
99997          5.7                  155         0  
99998          4.0                  100         0  
99999          6.6                   90         0  

[100000 rows x 9 columns]

In [5]:
data['gender'].value_counts()

gender
Female    58552
Male      41430
Other        18
Name: count, dtype: int64

In [6]:
data['smoking_history'].value_counts()

smoking_history
No Info        35816
never          35095
former          9352
current         9286
not current     6447
ever            4004
Name: count, dtype: int64

In [7]:
# One-hot encode Gender and Smokeing_history

In [8]:
data = data.join(pd.get_dummies(data.gender, dtype=int)).drop(['gender'],axis = 1)
data = data.join(pd.get_dummies(data.smoking_history, dtype=int)).drop(['smoking_history'],axis = 1)

In [9]:
# Normalize data

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
for col in data:
    data[col] = scaler.fit_transform(data[[col]])

In [11]:
# Shuffle data to create more randomness
data = data.sample(frac = 1)

In [12]:
data

age  hypertension  heart_disease       bmi  HbA1c_level  \
14662  0.249249           0.0            0.0  0.144024     0.490909   
250    0.374374           0.0            0.0  0.225607     0.563636   
638    0.361862           0.0            0.0  0.233077     0.236364   
16323  1.000000           0.0            0.0  0.140289     0.236364   
30585  0.637137           0.0            0.0  0.202031     0.472727   
...         ...           ...            ...       ...          ...   
82381  0.787287           0.0            0.0  0.166433     0.236364   
25953  0.662162           0.0            0.0  0.175537     0.272727   
28045  0.574575           0.0            0.0  0.223039     0.400000   
54458  0.612112           0.0            0.0  0.153945     0.000000   
65913  0.624625           0.0            0.0  0.240196     0.963636   

       blood_glucose_level  diabetes  Female  Male  Other  No Info  current  \
14662             0.045455       0.0     0.0   1.0    0.0      0.0      0.0   
250               0.272727       0.0     0.0   1.0    0.0      0.0      0.0   
638               0.045455       0.0     1.0   0.0    0.0      0.0      0.0   
16323             0.295455       0.0     0.0   1.0    0.0      0.0      0.0   
30585             0.022727       0.0     0.0   1.0    0.0      1.0      0.0   
...                    ...       ...     ...   ...    ...      ...      ...   
82381             0.340909       0.0     1.0   0.0    0.0      0.0      0.0   
25953             0.359091       0.0     0.0   1.0    0.0      0.0      0.0   
28045             0.209091       0.0     0.0   1.0    0.0      0.0      0.0   
54458             0.272727       0.0     0.0   1.0    0.0      0.0      0.0   
65913             0.295455       1.0     0.0   1.0    0.0      0.0      0.0   

       ever  former  never  not current  
14662   0.0     0.0    1.0          0.0  
250     0.0     0.0    1.0          0.0  
638     0.0     0.0    1.0          0.0  
16323   0.0     0.0    0.0          1.0  
30585   0.0     0.0    0.0          0.0  
...     ...     ...    ...          ...  
82381   0.0     0.0    1.0          0.0  
25953   1.0     0.0    0.0          0.0  
28045   0.0     1.0    0.0          0.0  
54458   0.0     1.0    0.0          0.0  
65913   0.0     0.0    1.0          0.0  

[100000 rows x 16 columns]

In [13]:
# Splitting data into train data and test data

In [14]:
train_data = data.iloc[:int(m*80/100),:]
test_data = data.iloc[int(m*80/100):,:]

In [15]:
X_train = np.array(train_data.drop(['diabetes'],axis = 1)).T
Y_train = np.array(train_data['diabetes'])

In [16]:
X_train

array([[0.24924925, 0.37437437, 0.36186186, ..., 0.8998999 , 0.13663664,
        0.54954955],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [17]:
Y_train

array([0., 0., 0., ..., 0., 0., 0.])

In [18]:
def init_params():
    W1 = np.random.randn(8,15)
    b1 = np.random.randn(8,1)
    W2 = np.random.randn(2,8)
    b2 = np.random.randn(2,1)
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z,0)
    
def Stable_Softmax(Z):
    c = np.max(Z)
    A = np.exp(Z-c) / sum(np.exp(Z-c))
    return A

def deriv_ReLU(Z):
    return Z > 0

def one_hot(Y):
    a = np.array(Y)
    b = np.where(a<1, 1, 0)
    one_hot_Y = np.array([b,a])
    return one_hot_Y

def foward_prob(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = Stable_Softmax(Z2)
    return Z1, A1, Z2, A2

def back_prob(Z1, A1, Z2, A2, W1, W2, X, Y):
    # derivative of Loss-Entropy w.r.t Z2, W2, b2, Z1, W1, b1
    dZ2 = A2 - one_hot(Y)
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate):
    # gradient descent
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    return W1, b1, W2, b2

In [19]:
def get_predictions(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, learning_rate, iter):
    W1, b1, W2, b2 = init_params()
    for i in range(iter):
        Z1, A1, Z2, A2 = foward_prob(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prob(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [20]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[1 1 1 ... 1 1 1] [0. 0. 0. ... 0. 0. 0.]
0.0848875
Iteration:  10
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.8894375
Iteration:  20
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.90065
Iteration:  30
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.90775
Iteration:  40
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.911325
Iteration:  50
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.91345
Iteration:  60
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.914625
Iteration:  70
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.9149125
Iteration:  80
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.9152
Iteration:  90
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.9153375
Iteration:  100
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.9155
Iteration:  110
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.9158375
Iteration:  120
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.916175
Iteration:  130
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.9167875
Iteration:  140
[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
0.917525
Iterati

In [21]:
def make_predictions(X, W1, b1, W2, b2):
    Z1, A1, Z2, A2 = foward_prob(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

X_test = np.array(test_data.drop(['diabetes'],axis = 1)).T
Y_test = np.array(test_data['diabetes'])

test_predictions = make_predictions(X_test, W1, b1, W2, b2)
get_accuracy(test_predictions, Y_test)

[0 0 0 ... 0 0 1] [1. 0. 0. ... 0. 0. 1.]


0.9499